language: rust

dist: bionic
sudo: required
addons:
  apt:
    packages:
    - libssl-dev

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
  - rust: nightly

cache: cargo

before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi

script:
- cargo clean
- cargo build
- cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    ./compute_coverage.sh
    bash <(curl -s https://codecov.io/bash)
  fi
