# https://docs.codecov.io/docs/common-recipe-list
coverage:
  status:
    project:
      default:
        target: 90%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target

    patch:
      default:
        enabled: no